# Copyright (c) 2016-2022 Martin Donath <martin.donath@squidfunk.com>

# Project information
site_name: Data Visualization 2024 Fall
site_url: https://github.com/haewoon/dviz-course-2024-fall
site_author: Haewoon Kwak
site_description: 

# Repository
repo_name: haewoon/dviz-course-2024-fall
repo_url: https://github.com/haewoon/dviz-course-2024-fall
edit_uri: ''


# Markdown extensions
markdown_extensions:
  - attr_list
  - admonition
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tabbed

# Extra javascript
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# Theme
theme:
  name: material
  language: en
  logo: images/dv.png
  favicon: images/dv.png
  features:
    - navigation.instant
    - navigation.top
    - content.code.annotate
    - search.suggest
    - search.highlight
  palette:
    # Light mode
    - media: '(prefers-color-scheme: light)'
      scheme: default
      primary: white
      accent: light blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Dark mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      primary: black
      accent: light blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/haewoon
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/haewoon
    - icon: fontawesome/solid/globe
      link: https://soda-labo.github.io

# Plugins
plugins:
  - mkdocs-jupyter:
      kernel_name: python3
  - search

# TOC
nav:
    - index.md
    - "1: Introduction":
        - m01-intro/class.md
        - m01-intro/lab01.ipynb
        - m01-intro/lab01supp-python_review.ipynb
    - "2: History":
        - m02-history/class.md
        - m02-history/lab02.ipynb
    - "3: Integrity":
        - m03-integrity/class.md
        - m03-integrity/lab03.ipynb
    - "4: Perception":
        - m04-perception/class.md
        - m04-perception/lab04.ipynb
    - "5: Design":
        - m05-design/class.md
        - m05-design/lab05.ipynb
    - "6: Data":
        - m06-data/class.md
        - m06-data/lab06.ipynb
    - "7: Univariate":
        - m07-1D/class.md
        - m07-1D/lab07.ipynb
    - "8: Histogram":
        - m08-histogram/class.md
        - m08-histogram/lab08.ipynb
    - "9: Estimation":
        - m09-estimation/class.md
        - m09-estimation/lab09.ipynb
    - "10: Logarithm":
        - m10-logscale/class.md
        - m10-logscale/lab10.ipynb
    - "11: High-dimensional data":
        - m11-highdim/class.md
        - m11-highdim/lab11.ipynb
    - "12: Maps":
        - m12-maps/class.md
        - m12-maps/lab12.ipynb
    - "13: Text":
        - m13-text/class.md
        - m13-text/lab13.ipynb
    - "14: Networks":
        - m14-networks/class.md
        - m14-networks/lab14.ipynb
    - "Appendix A: Project":
        - appendix-a/project-deliverables.md
        - appendix-a/types-of-projects.md
        - appendix-a/visualization-process.md





